### ISSUE TITLE
Share modal requires number

### ISSUE THREAD

**Issue by heyoung** [kieranwadia/upworkjob#1]
In the share modal, when we are adding someone to share with we need to name & number. Would it be better to require just the name as someone may not necessarily know their number?

**Comment by kieranwadia** [comment]
When someone shares their BirthPlan, it's going to be with people they're very close to, so they'll have their phone numbers. Additionally, the people they share with might not have an account (yet), so simply sharing by phone number ensures that when that other person signs in (also using their phone number) what's been already shared with them is readily available.
