### ISSUE TITLE
Card sidebar

### ISSUE THREAD

**Issue by heyoung** [kieranwadia/upworkjob#3]
For this part of the UI: 
![image](https://user-images.githubusercontent.com/8026353/109401205-31caa300-7945-11eb-8f50-608996cde736.png)

What API route is the source of the library of cards?

**Comment by kieranwadia** [comment]
/api/refdata

See the Fetching ReferenceData section of https://github.com/kieranwadia/upworkjob for more info about the shape of the data (or just hit the URL: http://s850604947.websitehome.co.uk/api/refdata)

**Comment by heyoung** [comment]
What is the source of the cards with no images? Is it the other properties (e.g 'placeofbirths')? If so what are they keywords for those?

**Comment by kieranwadia** [comment]
Currently, it would be the same source (i.e. `/api/refdata`, taking the `images` array) but where there is no filename, just show the defaultDescription. Is that okay? Or would a separate resource be better?

**Comment by heyoung** [comment]
Yeh that works, I'll treat the filename property as `filename: null | undefined | string`
