### ISSUE TITLE
Image location

### ISSUE THREAD

**Issue by heyoung** [kieranwadia/upworkjob#6]
For the images in refdata and birth plan what is the URL they are hosted at?

**Comment by kieranwadia** [comment]
Here, for example: http://s850604947.websitehome.co.uk/img/A.png

**Comment by heyoung** [comment]
That works. Just getting a 404 for http://s850604947.websitehome.co.uk/img/W.PNG

**Comment by kieranwadia** [comment]
W.PNG fixed now too.
