### ISSUE TITLE
POST /api/birthplans returns 400

### ISSUE THREAD

**Issue by heyoung** [kieranwadia/upworkjob#7]
Request:

Request URL: http://s850604947.websitehome.co.uk/api/birthplan?authId=86af32cf-d11e-49f4-8a45-40f2ad07c8fb
Request Method: POST
Status Code: 400 Bad Request

Body:
{"id":-99,"displayOrder":0,"name":"Unnamed Plan","title":"test title","layoutItems":[],"items":[]}

Response:
{"":["The input was not valid."]}

**Comment by kieranwadia** [comment]
Did you have Content-Type: application/json in the headers?

**Comment by heyoung** [comment]
That works
